config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: { registrations: "registrations"}
  resources :profiles, except: [:index, :show] do
    resources :life_stories, except: [:index, :show]
    resources :social_networks, except: [:index, :show]
    resources :projects, except: [:index, :show]
  end
   root 'hello_world#index'
  get 'hello_world', to: 'hello_world#index'
  get 'about-me', to: 'hello_world#index'
  get 'about-me/*life_story', to: 'hello_world#index'
  get 'blogs', to: 'hello_world#index'
  get 'portfolio', to: 'hello_world#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/life_story.rb
class LifeStory < ApplicationRecord
  belongs_to :profile
end

app/models/profile.rb
class Profile < ApplicationRecord
  has_one :life_story, dependent: :destroy
  has_many :social_networks, dependent: :destroy
  has_many :projects, dependent: :destroy

  def full_name_to_display
    first_name = self.first_name.capitalize
    middle_name = self.middle_name ? "#{self.middle_name.first.capitalize}." : ""
    last_name = self.last_name.capitalize
    "#{first_name} #{middle_name} #{last_name}"
  end

  def front_end_profile
    {
      id: self[:id],
      full_name: self.full_name_to_display,
      email: self[:email],
      phone_number: self[:phone_number],
      life_story: self.life_story,
      social_networks: self.social_networks,
      projects: self.projects
    }
  end

end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :profile
end

app/models/social_network.rb
class SocialNetwork < ApplicationRecord
  enum name: [:linkedin, :github, :twitter]

  belongs_to :profile
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_admin!
  protect_from_forgery with: :exception
  protect_from_forgery unless: -> { request.format.json? }
end

app/controllers/hello_world_controller.rb
# frozen_string_literal: true

class HelloWorldController < ApplicationController
  layout "hello_world"

  def index
    @signed_in = admin_signed_in?
    @profles = Profile.all
    profile = Profile.first
    @profile = profile.front_end_profile if profile
  end

end

app/controllers/life_stories_controller.rb
class LifeStoriesController < ApplicationController
  def new
    @profile = Profile.find(params[:profile_id])
    @life_story =  @profile.build_life_story
  end

  def edit
    @profile = Profile.find(params[:profile_id])
    @life_story =  @profile.life_story
  end

  def create
    @profile = Profile.find(params[:profile_id])
    @life_story = @profile.build_life_story(life_story_params)
    if @life_story.save
      redirect_to '/about-me/present'
    else
      render 'new'
    end
  end

  def update
    @life_story = LifeStory.find(params[:id])
    if @life_story.update(life_story_params)
      redirect_to '/about-me/present'
    else
      render 'edit'
    end
  end

  def destroy
    @life_story = LifeStory.find(params[:id])

    render json: {profile: nil} if @life_story.destroy
  end

  private

  def life_story_params
    params.require(:life_story).permit(:past, :presently, :future)
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def show
    @profile = Profile.first
    render json: @profile
  end

  def create
    redirect_to hello_world_path if Profile.all.count >= 1
    @profile = Profile.new(profile_params)
    @profile.save
    redirect_to hello_world_path
  end

  private

  def profile_params
    params.require(:profile).permit(:first_name, :middle_name, :last_name, :email, :phone_number)
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def new
    @profile = Profile.new
  end

  def create
    return redirect_to root_path if Profile.all.count >= 1
    @profile = Profile.new(profile_params)
    if @profile.save
      redirect_to hello_world_path
    else
      render 'new'
    end
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])
    if @profile.update(profile_params)
      redirect_to hello_world_path
    else
      render 'edit'
    end
  end

  def destroy
    @profile = Profile.find(params[:id])

    render json: {profile: nil} if @profile.destroy
  end

  private

  def profile_params
    params.require(:profile).permit(:first_name, :middle_name, :last_name, :email, :phone_number)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def new
    @profile = Profile.find(params[:profile_id])
    @project =  @profile.projects.new
  end

  def create
    @profile = Profile.find(params[:profile_id])
    techs =  params[:project][:technologies].split(',').map { |tech| tech.chomp  }
    proj_params = project_params
    proj_params[:technologies] = techs
    @project =  @profile.projects.new(proj_params)
    if @project.save
      redirect_to hello_world_path
    else
      render 'new'
    end
  end

  def edit
    @project =  Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    techs =  params[:project][:technologies].split(',').map { |tech| tech.chomp  }
    proj_params = project_params
    proj_params[:technologies] = techs
    if @project.update(proj_params)
      redirect_to '/about-me/'
    else
      render 'edit'
    end
  end

  def destroy
    @project = Project.find(params[:id])

    render json: {profile: nil} if @project.destroy
  end

  private

  def project_params
    params.require(:project).permit(:name, :technologies, :description ,:url_link)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  layout "hello_world"
  before_action :one_admin_registered?, only: [:new, :create]

  protected

  def one_admin_registered?
    if Admin.count >= 1
      if admin_signed_in?
        redirect_to root_path
      else
        redirect_to new_admin_session_path
      end
    end
  end

end

app/controllers/social_networks_controller.rb
class SocialNetworksController < ApplicationController
  def new
    @profile = Profile.find(params[:profile_id])
      @social_network =  @profile.social_networks.new
  end

  def create
    @profile = Profile.find(params[:profile_id])
    @social_network =  @profile.social_networks.new(social_network_params)
    if @social_network.save
      redirect_to '/about-me/'
    else
      render 'new'
    end
  end

  def edit
    @social_network =  SocialNetwork.find(params[:id])
  end

  def update
    @social_network = SocialNetwork.find(params[:id])
    if @social_network.update(social_network_params)
      redirect_to '/about-me/'
    else
      render 'edit'
    end
  end

  def destroy
    @social_network = SocialNetwork.find(params[:id])

    render json: {profile: nil} if @social_network.destroy
  end

  private
  def social_network_params
    params.require(:social_network).permit(:name, :url_link)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/life_stories_helper.rb
module LifeStoriesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper

  def tech_field(project)
    technologies_value = project.technologies ? @project[:technologies].join(',') : ""
    text_field(:project, :technologies, value: technologies_value)
  end

end

app/helpers/social_networks_helper.rb
module SocialNetworksHelper
end

app/views/hello_world/index.html.erb
<%= react_component("HelloWorld", props: {profile: @profile, signedIn: @signed_in}, prerender: false) %>

<div id='login-status' class="dark-bg">
  <p>
    <% if admin_signed_in? %>
      Logged in as: <strong><%= current_admin.email %></strong>
      </p>
      <p>
      <%= link_to 'Edit profile', edit_admin_registration_path, :class => 'navbar-link' %>
      <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Login", new_admin_session_path, :class => 'navbar-link'  %>
    <% end %>
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stevemcd87</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/layouts/hello_world.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Profile</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag 'hello-world' %>
    <%= javascript_pack_tag 'hello-world-bundle' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/life_stories/_form.html.erb
<%= form_with(model: [ @profile, @life_story], local: true) do |form| %>
  <%#= error_message_for(@life_story) %>
  <p>
    <%= form.label :past %><br>
    <%= form.text_area :past %>
  </p>
  <p>
    <%= form.label :present %><br>
    <%= form.text_area :presently %>
  </p>
  <p>
    <%= form.label :future %><br>
    <%= form.text_area :future %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/life_stories/edit.html.erb
<h2>Edit your Life Stories</h2>
<h3>HTML will be parsed</h3>

<%= render 'form' %>

app/views/life_stories/new.html.erb
<h2>Tell us about yourself</h2>

<%= render 'form' %>

app/views/profiles/_form.html.erb
<%= form_with model: @profile, local: true do |form| %>

  <p>
    <%= form.label :first_name %><br>
    <%= form.text_field :first_name %>
  </p>

  <p>
    <%= form.label :middle_name %><br>
    <%= form.text_field :middle_name %>
  </p>

  <p>
    <%= form.label :last_name %><br>
    <%= form.text_field :last_name %>
  </p>

  <p>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </p>

  <p>
    <%= form.label :phone_number %><br>
    <%= form.text_field :phone_number %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/profiles/edit.html.erb
<h2>Edit your Profile</h2>

<%= render 'form' %>

app/views/profiles/new.html.erb
<h2>Create your Profile</h2>

<%= render 'form' %>

app/views/projects/_form.html.erb
<%= form_with(model: [ :profile, @project], local: true) do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :technologies %><br>
    <%= tech_field(@project) %>
  </p>
  <p>
    <%= form.label :description %><br>
    <%= form.text_field :description %>
  </p>
  <p>
    <%= form.label :url_link %><br>
    <%= form.text_field :url_link %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= render 'form' %>

app/views/projects/new.html.erb
Create a Project

<%= render 'form' %>

app/views/social_networks/_form.html.erb
<%= form_with(model: [ :profile, @social_network], local: true) do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.select :name, SocialNetwork.names.keys.to_a %>
  </p>
  <p>
    <%= form.label :url_link %><br>
    <%= form.text_field :url_link %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/social_networks/edit.html.erb
<h2>Edit Social Network</h2>

<%= render 'form' %>

app/views/social_networks/new.html.erb
<h2>Create a Social Network of yours</h2>

<%= render 'form' %>